# Generated by Django 3.1.3 on 2020-11-21 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epic.joincode')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.PositiveBigIntegerField()),
                ('last_known_nickname', models.CharField(max_length=250)),
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('notify', models.BooleanField(default=False)),
                ('daily', models.BooleanField(default=True)),
                ('weekly', models.BooleanField(default=True)),
                ('lootbox', models.BooleanField(default=True)),
                ('vote', models.BooleanField(default=True)),
                ('hunt', models.BooleanField(default=True)),
                ('adventure', models.BooleanField(default=True)),
                ('training', models.BooleanField(default=True)),
                ('duel', models.BooleanField(default=True)),
                ('quest', models.BooleanField(default=True)),
                ('work', models.BooleanField(default=True)),
                ('horse', models.BooleanField(default=True)),
                ('arena', models.BooleanField(default=True)),
                ('dungeon', models.BooleanField(default=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.server')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoolDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('lootbox', 'lootbox'), ('vote', 'vote'), ('hunt', 'hunt'), ('adventure', 'adventure'), ('quest', 'quest'), ('training', 'training'), ('duel', 'duel'), ('mine', 'work'), ('horse', 'horse'), ('arena', 'arena'), ('dungeon', 'dungeon')], max_length=10)),
                ('after', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.profile')),
            ],
            options={
                'unique_together': {('profile', 'type')},
            },
        ),
    ]
