# Generated by Django 3.1.3 on 2020-11-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0005_guild_cooldowns'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_format',
            field=models.CharField(default='%I:%M:%S %p, %m/%d', max_length=50),
        ),
        migrations.AlterField(
            model_name='cooldown',
            name='type',
            field=models.CharField(choices=[('daily', 'Time for your daily! :sun_with_face:'), ('weekly', "Looks like it's that time of the week... :newspaper:"), ('lootbox', 'Lootbox! :moneybag:'), ('vote', 'You can vote again. :ballot_box:'), ('hunt', 'is on the hunt! :crossed_swords:'), ('adventure', "Let's go on an adventure! :woman_running:"), ('quest', 'The townspeople need our help! '), ('training', 'want to get buff? :man_lifting_weights:'), ('duel', "It's time to d-d-d-d-duel! :crossed_swords:"), ('work', 'Get back to work. :pick:'), ('horse', 'Pie-O-My! :horse_racing:'), ('arena', 'Heeyyyy lets go hurt each other. :circus_tent:'), ('dungeon', 'can you reach the next area? :exclamation:'), ('guild', "Hey, those people are different! Get 'em! :shield:")], max_length=10),
        ),
    ]
