# Generated by Django 3.1.3 on 2020-11-29 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0010_hunt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('horse', 'horse'), ('dungeon', 'dungeon'), ('miniboss', 'miniboss'), ('arena', 'arena'), ('duel', 'duel')], max_length=8)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.groupactivity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.profile')),
            ],
        ),
    ]
