# Generated by Django 3.1.3 on 2020-12-24 20:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0012_event_cooldowns'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cooldown_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
    ]
