# Generated by Django 3.1.3 on 2021-03-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("epic", "0017_pet_cd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentinel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trigger", models.PositiveSmallIntegerField(choices=[(0, "Inventory"), (1, "Time")])),
                ("after", models.DateTimeField(blank=True, null=True)),
                ("action", models.CharField(blank=True, max_length=10, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="epic.profile")),
            ],
        ),
    ]
