# Generated by Django 3.1.7 on 2022-01-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epic", "0019_farm"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="banned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="sentinel",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[("logs", "Logs"), ("can_craft", "Can Craft"), ("how_many", "How Many")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sentinel",
            name="trigger",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Inventory"), (1, "Time"), (3, "Registration Confirmation")]
            ),
        ),
    ]
