# Generated by Django 3.1.7 on 2022-01-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epic", "0020_bans"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cooldown_multipliers",
            field=models.JSONField(default=dict),
        ),
    ]
