# Generated by Django 3.1.7 on 2022-01-16 19:38

from django.db import migrations, models
import django.db.models.deletion


def seed_areas(apps, schema):
    Area = apps.get_model("epic", "Area")
    Dungeon = apps.get_model("epic", "Dungeon")
    areas = [
        Area(ascended_activities=["dynamite"], activities=["chop"]),
        Area(ascended_activities=["dynamite"], activities=["chop"]),
        Area(
            trades=["dismantle all logs and fruit, even big logs", "trade to fish"],
            ascended_activities=["dynamite"],
            activities=["axe"],
        ),
        Area(ascended_activities=["dynamite"], activities=["axe"]),
        Area(
            trades=["dismantle all logs and fish, even big ones", "trade to apple (don't forget rubies!)"],
            ascended_activities=["dynamite"],
            activities=["axe", "buy edgy lootboxes", "do **not** sell rubies"],
        ),
        Area(
            ascended_activities=["greenhouse"],
            activities=["ladder if you have more than 20m coins", "pickaxe otherwise"],
        ),
        Area(
            trades=["dismantle bananas", "trade to logs"],
            ascended_activities=["greenhouse"],
            activities=["ladder if you have more than 20m coins", "pickaxe otherwise"],
        ),
        Area(
            trades=["dismantle all fish and all logs mega or lower (include hyper if crafter 90+)", "trade to apple"],
            ascended_activities=["dynamite"],
            activities=["bowsaw if you have more than 20m coins", "pickaxe otherwise"],
        ),
        Area(
            trades=["dismantle bananas and epic logs (and super logs if crafter 90+)", "trade to fish"],
            ascended_activities=["dynamite"],
            activities=["chainsaw if you have more than 20m coins", "pickaxe otherwise"],
        ),
        Area(
            trades=["dismantle bananas", "trade to logs"],
            ascended_activities=["chainsaw if you need big logs to craft ultra-edgy for D11+", "dynamite otherwise"],
            activities=["chainsaw if you have more than 30m coins", "drill otherwise"],
        ),
        Area(
            trades=["trade rubies to something else"],
            ascended_activities=["chainsaw if you need big logs to craft ultra-edgy for D11+", "dynamite otherwise"],
            activities=["chainsaw if you have more than 30m coins", "drill otherwise"],
        ),
        Area(
            ascended_activities=[
                "chainsaw if you need big logs",
                "greenhouse if you need HP (fruit salad)",
                "dynamite if you need money",
            ],
            activities=["chainsaw if you don't need money", "dynamite otherwise"],
        ),
        Area(
            ascended_activities=[
                "chainsaw if you need big logs",
                "greenhouse if you need HP (fruit salad)",
                "dynamite if you need money",
            ],
            activities=["chainsaw if you don't need money", "dynamite otherwise"],
        ),
        Area(
            ascended_activities=[
                "chainsaw if you need big logs",
                "greenhouse if you need HP (fruit salad)",
                "dynamite if you need money",
            ],
            activities=["chainsaw if you don't need money", "dynamite otherwise"],
        ),
        Area(
            ascended_activities=[
                "chainsaw if you need big logs",
                "greenhouse if you need HP (fruit salad)",
                "dynamite if you need money",
            ],
            activities=["chainsaw if you don't need money", "dynamite otherwise"],
        ),
    ]
    for i, area in enumerate(areas):
        area.id = i + 1
    Area.objects.bulk_create(areas)
    dungeons = [
        Dungeon(
            level=5,
            sword="Wooden Sword [No Enchantment]",
            armor="Fish Armor [No Enchantment]",
            attack=9,
            defense=14,
            life=120,
            carry=30,
        ),
        Dungeon(
            level=10, sword="Fish Sword [Epic]", armor="Wolf Armor [Epic]", attack=37, defense=48, life=145, carry=50
        ),
        Dungeon(
            level=15, sword="Zombie Sword [Epic]", armor="Epic Armor [Epic]", attack=93, defense=91, life=170, carry=85
        ),
        Dungeon(
            level=20,
            sword="Zombie Sword [Epic]",
            armor="Epic Armor [Hyper]",
            attack=101,
            defense=105,
            life=195,
            carry=125,
        ),
        Dungeon(
            level=30,
            sword="Unicorn Sword [Hyper]",
            armor="Epic Armor [Ultimate]",
            attack=190,
            defense=130,
            life=270,
            carry=169,
        ),
        Dungeon(
            level=30,
            sword="Unicorn Sword [Hyper]",
            armor="Coin Armor [Ultimate]",
            attack=190,
            defense=176,
            life=270,
            carry=210,
        ),
        Dungeon(
            level=40,
            sword="Unicorn Sword [Ultimate]",
            armor="Mermaid Armor [Perfect]",
            attack=220,
            defense=234,
            life=295,
            carry=240,
        ),
        Dungeon(
            level=55,
            sword="Unicorn Sword [Ultimate]",
            armor="Mermaid Armor [Perfect]",
            attack=247,
            defense=262,
            life=420,
            carry=275,
        ),
        Dungeon(
            level=55,
            sword="Unicorn Sword [Ultimate]",
            armor="Edgy Armor [Hyper]",
            attack=247,
            defense=433,
            life=370,
            carry=330,
        ),
        Dungeon(
            level=50,
            sword="Edgy Sword [No Enchantment]",
            armor="Edgy Armor [No Enchantment]",
            attack=None,
            defense=None,
            life=None,
            carry=None,
        ),
        Dungeon(level=70, sword="Ultra-Edgy Sword [Hyper]", armor=None, attack=629, defense=None, life=900, carry=None, description=
        """
:fire::stop_button::fire::stop_button::fire::stop_button::fire::stop_button::dragon_face:
:stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button:
:stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button:
:stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button:
:stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button:
:stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button:
:stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button:
:stop_button::crossed_swords::stop_button::stop_button::stop_button::stop_button::stop_button::stop_button:
[You will need to dodge some fireballs. Each does flat 100 damage. Passing a turn is 10 damage.](https://epic-rpg.fandom.com/wiki/Dungeon_11)
"""),
        Dungeon(
            level=80,
            sword=None,
            armor="Ultra-Edgy Armor [No Enchantment]",
            attack=None,
            defense=722,
            life=900,
            carry=None,
            description="""
:white_large_square::dragon_face::white_large_square:
:fire::fire::fire:
:white_large_square::white_square_button::white_large_square:
:white_square_button::shirt::black_square_button:
:black_square_button::black_large_square::black_square_button:

:black_square_button: -> +5 HP, -5 :low_brightness: orb
:white_square_button: -> -500 HP
:black_large_square: -> +1 :low_brightness: orb, -25 HP
:white_large_square: -> nothing
[More Info](https://epic-rpg.fandom.com/wiki/Dungeon_12)            
            """
        ),
        Dungeon(
            level=100,
            sword="Omega Sword [No Enchantment]",
            armor=None,
            attack=None,
            defense=None,
            life=1001,
            carry=None,
            description="""
This is a horrible quiz show.
• Choosing the correct answer will move you 1 room closer when the room number is even, otherwise 2 rooms further
• Choosing the wrong (but not so wrong) answer will move you 4 rooms further when the room number is lower than 9, otherwise 1 room closer
• Choosing the wrong answer will move you 2 rooms closer when the dragon is at least 8 rooms away from you, 5 rooms further when the dragon is 3 or less rooms away, otherwise you won't move
[More Info](https://epic-rpg.fandom.com/wiki/Dungeon_13)            
                """
        ),
        Dungeon(
            level=100, sword=None, armor="Omega Armor [Ultra-Edgy+]", attack=None, defense=1000, life=2000, carry=None, description="""
:brown_square::dragon_face::brown_square::brown_square::brown_square::brown_square::dragon_face::brown_square:
:purple_square::purple_square::purple_square::blue_square::purple_square::yellow_square::yellow_square::yellow_square:
:yellow_square::red_square::blue_square::purple_square::green_square::orange_square::green_square::brown_square:
:orange_square::purple_square::orange_square::green_square::orange_square::red_square::blue_square::purple_square:
:orange_square::yellow_square::yellow_square::orange_square::orange_square::green_square::brown_square::purple_square:
:orange_square::green_square::blue_square::green_square::green_square::green_square::purple_square::brown_square:
:blue_square::brown_square::purple_square::brown_square::brown_square::brown_square::brown_square::purple_square:
:orange_square::blue_square::shirt::orange_square::orange_square::red_square::red_square::orange_square:
Each square has a different effect when you step on it.
[More Info](https://epic-rpg.fandom.com/wiki/Dungeon_14)
            """
        ),
        Dungeon(
            area_id=15,
            level=200,
            name="D15.1",
            sword="Ultra-Omega Sword",
            armor="Ultra-Omega Armor",
            attack=None,
            defense=None,
            life=None,
            carry=None,
            description="""
:yellow_square::green_square::yellow_square::green_square::yellow_square::green_square::yellow_square::green_square:
:red_square::blue_square::cat::blue_square::red_square::blue_square::red_square::blue_square:
:yellow_square::shirt::dragon_face::dog2::yellow_square::green_square::yellow_square::green_square:
:red_square::blue_square::dragon::blue_square::red_square::blue_square::red_square::blue_square:
:yellow_square::green_square::yellow_square::green_square::yellow_square::green_square::yellow_square::green_square:
:red_square::blue_square::red_square::blue_square::red_square::blue_square::red_square::blue_square:
:yellow_square::green_square::yellow_square::green_square::yellow_square::green_square::yellow_square::green_square:
:red_square::blue_square::red_square::blue_square::red_square::blue_square::red_square::blue_square:
[You have to surround the dragon with your pets.](https://epic-rpg.fandom.com/wiki/Dungeon_15.1)
            """
        ),
        Dungeon(
            area_id=15,
            level=200,
            name="D15.2",
            sword="Ultra-Omega Sword",
            armor="Ultra-Omega Armor",
            attack=None,
            defense=None,
            life=None,
            carry=None,
            description="[More Info](https://epic-rpg.fandom.com/wiki/Dungeon_15.2)"
        ),
    ]
    for i, dungeon in enumerate(dungeons):
        dungeon.area_id = i + 1 if not dungeon.area_id else dungeon.area_id
        dungeon.name = f"D{i + 1}" if not dungeon.name else dungeon.name
    Dungeon.objects.bulk_create(dungeons)


class Migration(migrations.Migration):

    dependencies = [
        ("epic", "0021_event_multipliers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                (
                    "trades",
                    models.JSONField(blank=True, help_text="What to dismantle and trade before leaving", null=True),
                ),
                (
                    "activities",
                    models.JSONField(blank=True, help_text="What you should do while you are here", null=True),
                ),
                (
                    "ascended_activities",
                    models.JSONField(blank=True, help_text="What you should do if ascended", null=True),
                ),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.CreateModel(
            name="Dungeon",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("level", models.PositiveSmallIntegerField(help_text="recommended level")),
                ("sword", models.CharField(blank=True, help_text="recommended sword", max_length=100, null=True)),
                ("armor", models.CharField(blank=True, help_text="recommended armor", max_length=100, null=True)),
                ("attack", models.PositiveSmallIntegerField(blank=True, help_text="recommended attack", null=True)),
                ("defense", models.PositiveSmallIntegerField(blank=True, help_text="recommended defense", null=True)),
                ("life", models.PositiveSmallIntegerField(blank=True, help_text="recommended life", null=True)),
                ("carry", models.PositiveSmallIntegerField(blank=True, help_text="dungeon defense", null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="dungeons", to="epic.area"
                    ),
                ),
            ],
        ),
        migrations.RunPython(seed_areas, migrations.RunPython.noop),
    ]
